interface Currency {
  code: string;
  name: string;
  decimal_digits: number;
  symbol: string;
}

const currencies: Currency[] = [
  {
    code: "AED",
    name: "United Arab Emirates Dirham",
    decimal_digits: 2,
    symbol: "د.إ",
  },
  {
    code: "AFN",
    name: "Afghan Afghani",
    decimal_digits: 2,
    symbol: "؋",
  },
  {
    code: "ALL",
    name: "Albanian Lek",
    decimal_digits: 2,
    symbol: "L",
  },
  {
    code: "AMD",
    name: "Armenian Dram",
    decimal_digits: 2,
    symbol: "֏",
  },
  {
    code: "ANG",
    name: "Netherlands Antillean Guilder",
    decimal_digits: 2,
    symbol: "ƒ",
  },
  {
    code: "AOA",
    name: "Angolan Kwanza",
    decimal_digits: 2,
    symbol: "Kz",
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "AWG",
    name: "Aruban Florin",
    decimal_digits: 2,
    symbol: "ƒ",
  },
  {
    code: "AZN",
    name: "Azerbaijani Manat",
    decimal_digits: 2,
    symbol: "₼",
  },
  {
    code: "BAM",
    name: "Bosnia-Herzegovina Convertible Mark",
    decimal_digits: 2,
    symbol: "KM",
  },
  {
    code: "BBD",
    name: "Barbadian Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    decimal_digits: 2,
    symbol: "৳",
  },
  {
    code: "BGN",
    name: "Bulgarian Lev",
    decimal_digits: 2,
    symbol: "лв",
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    decimal_digits: 3,
    symbol: "ب.د",
  },
  {
    code: "BIF",
    name: "Burundian Franc",
    decimal_digits: 0,
    symbol: "Fr",
  },
  {
    code: "BMD",
    name: "Bermudian Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "BND",
    name: "Brunei Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "BOB",
    name: "Bolivian Boliviano",
    decimal_digits: 2,
    symbol: "Bs.",
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    decimal_digits: 2,
    symbol: "R$",
  },
  {
    code: "BSD",
    name: "Bahamian Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "BTN",
    name: "Bhutanese Ngultrum",
    decimal_digits: 2,
    symbol: "Nu.",
  },
  {
    code: "BWP",
    name: "Botswanan Pula",
    decimal_digits: 2,
    symbol: "P",
  },
  {
    code: "BYN",
    name: "Belarusian Ruble",
    decimal_digits: 2,
    symbol: "Br",
  },
  {
    code: "BZD",
    name: "Belize Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "CDF",
    name: "Congolese Franc",
    decimal_digits: 2,
    symbol: "Fr",
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    decimal_digits: 2,
    symbol: "Fr.",
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    decimal_digits: 0,
    symbol: "$",
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    decimal_digits: 2,
    symbol: "¥",
  },
  {
    code: "COP",
    name: "Colombian Peso",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    decimal_digits: 2,
    symbol: "₡",
  },
  {
    code: "CUC",
    name: "Cuban Convertible Peso",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "CUP",
    name: "Cuban Peso",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "CVE",
    name: "Cape Verdean Escudo",
    decimal_digits: 2,
    symbol: "Esc",
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    decimal_digits: 2,
    symbol: "Kč",
  },
  {
    code: "DJF",
    name: "Djiboutian Franc",
    decimal_digits: 0,
    symbol: "Fr",
  },
  {
    code: "DKK",
    name: "Danish Krone",
    decimal_digits: 2,
    symbol: "kr",
  },
  {
    code: "DOP",
    name: "Dominican Peso",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "DZD",
    name: "Algerian Dinar",
    decimal_digits: 2,
    symbol: "د.ج",
  },
  {
    code: "EGP",
    name: "Egyptian Pound",
    decimal_digits: 2,
    symbol: "ج.م",
  },
  {
    code: "ERN",
    name: "Eritrean Nakfa",
    decimal_digits: 2,
    symbol: "Nfk",
  },
  {
    code: "ETB",
    name: "Ethiopian Birr",
    decimal_digits: 2,
    symbol: "Br",
  },
  {
    code: "EUR",
    name: "Euro",
    decimal_digits: 2,
    symbol: "€",
  },
  {
    code: "FJD",
    name: "Fijian Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "FKP",
    name: "Falkland Islands Pound",
    decimal_digits: 2,
    symbol: "£",
  },
  {
    code: "GBP",
    name: "British Pound",
    decimal_digits: 2,
    symbol: "£",
  },
  {
    code: "GEL",
    name: "Georgian Lari",
    decimal_digits: 2,
    symbol: "₾",
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    decimal_digits: 2,
    symbol: "GH₵",
  },
  {
    code: "GIP",
    name: "Gibraltar Pound",
    decimal_digits: 2,
    symbol: "£",
  },
  {
    code: "GMD",
    name: "Gambian Dalasi",
    decimal_digits: 2,
    symbol: "D",
  },
  {
    code: "GNF",
    name: "Guinean Franc",
    decimal_digits: 0,
    symbol: "Fr",
  },
  {
    code: "GTQ",
    name: "Guatemalan Quetzal",
    decimal_digits: 2,
    symbol: "Q",
  },
  {
    code: "GYD",
    name: "Guyanese Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "HNL",
    name: "Honduran Lempira",
    decimal_digits: 2,
    symbol: "L",
  },
  {
    code: "HRK",
    name: "Croatian Kuna",
    decimal_digits: 2,
    symbol: "kn",
  },
  {
    code: "HTG",
    name: "Haitian Gourde",
    decimal_digits: 2,
    symbol: "G",
  },
  {
    code: "HUF",
    name: "Hungarian Forint",
    decimal_digits: 2,
    symbol: "Ft",
  },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    decimal_digits: 2,
    symbol: "Rp",
  },
  {
    code: "ILS",
    name: "Israeli New Shekel",
    decimal_digits: 2,
    symbol: "₪",
  },
  {
    code: "INR",
    name: "Indian Rupee",
    decimal_digits: 2,
    symbol: "₹",
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    decimal_digits: 3,
    symbol: "ع.د",
  },
  {
    code: "IRR",
    name: "Iranian Rial",
    decimal_digits: 2,
    symbol: "﷼",
  },
  {
    code: "ISK",
    name: "Icelandic Króna",
    decimal_digits: 0,
    symbol: "kr",
  },
  {
    code: "JMD",
    name: "Jamaican Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    decimal_digits: 3,
    symbol: "د.ا",
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    decimal_digits: 0,
    symbol: "¥",
  },
  {
    code: "KES",
    name: "Kenyan Shilling",
    decimal_digits: 2,
    symbol: "KSh",
  },
  {
    code: "KGS",
    name: "Kyrgyzstani Som",
    decimal_digits: 2,
    symbol: "сом",
  },
  {
    code: "KHR",
    name: "Cambodian Riel",
    decimal_digits: 2,
    symbol: "៛",
  },
  {
    code: "KMF",
    name: "Comorian Franc",
    decimal_digits: 0,
    symbol: "Fr",
  },
  {
    code: "KPW",
    name: "North Korean Won",
    decimal_digits: 2,
    symbol: "₩",
  },
  {
    code: "KRW",
    name: "South Korean Won",
    decimal_digits: 0,
    symbol: "₩",
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    decimal_digits: 3,
    symbol: "د.ك",
  },
  {
    code: "KYD",
    name: "Cayman Islands Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    decimal_digits: 2,
    symbol: "₸",
  },
  {
    code: "LAK",
    name: "Lao Kip",
    decimal_digits: 2,
    symbol: "₭",
  },
  {
    code: "LBP",
    name: "Lebanese Pound",
    decimal_digits: 2,
    symbol: "ل.ل",
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    decimal_digits: 2,
    symbol: "රු",
  },
  {
    code: "LRD",
    name: "Liberian Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "LSL",
    name: "Lesotho Loti",
    decimal_digits: 2,
    symbol: "L",
  },
  {
    code: "LYD",
    name: "Libyan Dinar",
    decimal_digits: 3,
    symbol: "ل.د",
  },
  {
    code: "MAD",
    name: "Moroccan Dirham",
    decimal_digits: 2,
    symbol: "د.م.",
  },
  {
    code: "MDL",
    name: "Moldovan Leu",
    decimal_digits: 2,
    symbol: "L",
  },
  {
    code: "MGA",
    name: "Malagasy Ariary",
    decimal_digits: 2,
    symbol: "Ar",
  },
  {
    code: "MKD",
    name: "Macedonian Denar",
    decimal_digits: 2,
    symbol: "ден",
  },
  {
    code: "MMK",
    name: "Myanmar Kyat",
    decimal_digits: 2,
    symbol: "K",
  },
  {
    code: "MNT",
    name: "Mongolian Tögrög",
    decimal_digits: 2,
    symbol: "₮",
  },
  {
    code: "MOP",
    name: "Macanese Pataca",
    decimal_digits: 2,
    symbol: "P",
  },
  {
    code: "MRU",
    name: "Mauritanian Ouguiya",
    decimal_digits: 2,
    symbol: "UM",
  },
  {
    code: "MUR",
    name: "Mauritian Rupee",
    decimal_digits: 2,
    symbol: "₨",
  },
  {
    code: "MVR",
    name: "Maldivian Rufiyaa",
    decimal_digits: 2,
    symbol: "ރ",
  },
  {
    code: "MWK",
    name: "Malawian Kwacha",
    decimal_digits: 2,
    symbol: "MK",
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    decimal_digits: 2,
    symbol: "RM",
  },
  {
    code: "MZN",
    name: "Mozambican Metical",
    decimal_digits: 2,
    symbol: "MT",
  },
  {
    code: "NAD",
    name: "Namibian Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    decimal_digits: 2,
    symbol: "₦",
  },
  {
    code: "NIO",
    name: "Nicaraguan Córdoba",
    decimal_digits: 2,
    symbol: "C$",
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    decimal_digits: 2,
    symbol: "kr",
  },
  {
    code: "NPR",
    name: "Nepalese Rupee",
    decimal_digits: 2,
    symbol: "रू",
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "OMR",
    name: "Omani Rial",
    decimal_digits: 3,
    symbol: "ر.ع.",
  },
  {
    code: "PAB",
    name: "Panamanian Balboa",
    decimal_digits: 2,
    symbol: "B/.",
  },
  {
    code: "PEN",
    name: "Peruvian Sol",
    decimal_digits: 2,
    symbol: "S/.",
  },
  {
    code: "PGK",
    name: "Papua New Guinean Kina",
    decimal_digits: 2,
    symbol: "K",
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    decimal_digits: 2,
    symbol: "₱",
  },
  {
    code: "PKR",
    name: "Pakistani Rupee",
    decimal_digits: 2,
    symbol: "₨",
  },
  {
    code: "PLN",
    name: "Polish Złoty",
    decimal_digits: 2,
    symbol: "zł",
  },
  {
    code: "PYG",
    name: "Paraguayan Guaraní",
    decimal_digits: 0,
    symbol: "₲",
  },
  {
    code: "QAR",
    name: "Qatari Riyal",
    decimal_digits: 2,
    symbol: "ر.ق",
  },
  {
    code: "RON",
    name: "Romanian Leu",
    decimal_digits: 2,
    symbol: "lei",
  },
  {
    code: "RSD",
    name: "Serbian Dinar",
    decimal_digits: 2,
    symbol: "дин.",
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    decimal_digits: 2,
    symbol: "₽",
  },
  {
    code: "RWF",
    name: "Rwandan Franc",
    decimal_digits: 0,
    symbol: "Fr",
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    decimal_digits: 2,
    symbol: "ر.س",
  },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "SCR",
    name: "Seychellois Rupee",
    decimal_digits: 2,
    symbol: "₨",
  },
  {
    code: "SDG",
    name: "Sudanese Pound",
    decimal_digits: 2,
    symbol: "ج.س.",
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    decimal_digits: 2,
    symbol: "kr",
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "SHP",
    name: "Saint Helena Pound",
    decimal_digits: 2,
    symbol: "£",
  },
  {
    code: "SLL",
    name: "Sierra Leonean Leone",
    decimal_digits: 2,
    symbol: "Le",
  },
  {
    code: "SOS",
    name: "Somali Shilling",
    decimal_digits: 2,
    symbol: "Sh",
  },
  {
    code: "SRD",
    name: "Surinamese Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "SSP",
    name: "South Sudanese Pound",
    decimal_digits: 2,
    symbol: "£",
  },
  {
    code: "STN",
    name: "São Tomé and Príncipe Dobra",
    decimal_digits: 2,
    symbol: "Db",
  },
  {
    code: "SVC",
    name: "Salvadoran Colón",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "SYP",
    name: "Syrian Pound",
    decimal_digits: 2,
    symbol: "ل.س",
  },
  {
    code: "SZL",
    name: "Swazi Lilangeni",
    decimal_digits: 2,
    symbol: "L",
  },
  {
    code: "THB",
    name: "Thai Baht",
    decimal_digits: 2,
    symbol: "฿",
  },
  {
    code: "TJS",
    name: "Tajikistani Somoni",
    decimal_digits: 2,
    symbol: "SM",
  },
  {
    code: "TMT",
    name: "Turkmenistani Manat",
    decimal_digits: 2,
    symbol: "m",
  },
  {
    code: "TND",
    name: "Tunisian Dinar",
    decimal_digits: 3,
    symbol: "د.ت",
  },
  {
    code: "TOP",
    name: "Tongan Paʻanga",
    decimal_digits: 2,
    symbol: "T$",
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    decimal_digits: 2,
    symbol: "₺",
  },
  {
    code: "TTD",
    name: "Trinidad and Tobago Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "TVD",
    name: "Tuvaluan Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "TWD",
    name: "New Taiwan Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    decimal_digits: 2,
    symbol: "TSh",
  },
  {
    code: "UAH",
    name: "Ukrainian Hryvnia",
    decimal_digits: 2,
    symbol: "₴",
  },
  {
    code: "UGX",
    name: "Ugandan Shilling",
    decimal_digits: 0,
    symbol: "USh",
  },
  {
    code: "USD",
    name: "United States Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "UYU",
    name: "Uruguayan Peso",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "UZS",
    name: "Uzbekistani So'm",
    decimal_digits: 2,
    symbol: "soʻm",
  },
  {
    code: "VES",
    name: "Venezuelan Bolívar Soberano",
    decimal_digits: 2,
    symbol: "Bs.S",
  },
  {
    code: "VND",
    name: "Vietnamese Đồng",
    decimal_digits: 0,
    symbol: "₫",
  },
  {
    code: "VUV",
    name: "Vanuatu Vatu",
    decimal_digits: 0,
    symbol: "Vt",
  },
  {
    code: "WST",
    name: "Samoan Tala",
    decimal_digits: 2,
    symbol: "T",
  },
  {
    code: "XAF",
    name: "Central African CFA Franc",
    decimal_digits: 0,
    symbol: "Fr",
  },
  {
    code: "XCD",
    name: "East Caribbean Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
  {
    code: "XOF",
    name: "West African CFA Franc",
    decimal_digits: 0,
    symbol: "Fr",
  },
  {
    code: "XPF",
    name: "CFP Franc",
    decimal_digits: 0,
    symbol: "Fr",
  },
  {
    code: "YER",
    name: "Yemeni Rial",
    decimal_digits: 2,
    symbol: "﷼",
  },
  {
    code: "ZAR",
    name: "South African Rand",
    decimal_digits: 2,
    symbol: "R",
  },
  {
    code: "ZMW",
    name: "Zambian Kwacha",
    decimal_digits: 2,
    symbol: "ZK",
  },
  {
    code: "ZWL",
    name: "Zimbabwean Dollar",
    decimal_digits: 2,
    symbol: "$",
  },
];

export default currencies;
