


// Import all necessary Lucide icons
import {
  Briefcase, 
  PenTool, 
  LineChart, 
  Home, 
  Building, 
  DollarSign, 
  Percent, 
  Gift, 
  RotateCcw, 
  Coins,
  ShoppingCart, 
  Coffee, 
  Plug, 
  Banknote, 
  Car, 
  Shield, 
  Heart, 
  BookOpen, 
  Baby, 
  Film, 
  Plane, 
  Shirt,
  Scissors, 
  Repeat, 
  HandHeart, 
  Wrench, 
  Smartphone, 
  Sofa, 
  PawPrint, 
  Dumbbell, 
  Book, 
  Music, 
  Gamepad,
  Palette, 
  FileText, 
  Wifi, 
  Tv, 
  PlayCircle, 
  ParkingCircle, 
  Map, 
  Bus, 
  AlertTriangle, 
  CreditCard,
  PiggyBank, 
  TrendingUp, 
  LifeBuoy, 
  Calendar, 
  Snowflake, 
  Egg, 
  Dice1, 
  Wine, 
  Cigarette, 
  Candy,
  Umbrella, 
  Hotel,

  // New Icons to import for the expanded list
  Fuel, 
  ShieldCheck, 
  Settings2, 
  ShieldPlus, 
  Landmark, 
  GraduationCap, 
  PaintRoller, 
  ShoppingBasket,
  ArrowRightLeft, 
  Award, 
  Scale, 
  Mail, 
  AppWindow, 
  Wallet, 
  Utensils, 
  MoreHorizontal,
  Receipt, 
  // Added Receipt icon

  type LucideIcon,
} from "lucide-react";

// Updated iconMap with new and existing icons
export const iconMap: Record<string, 
LucideIcon> = {
  "briefcase": Briefcase,
  "pen-tool": PenTool,
  "line-chart": LineChart,
  "home": Home,
  "building": Building,
  "dollar-sign": DollarSign,
  "percent": Percent,
  "gift": Gift,
  "rotate-ccw": RotateCcw,
  "coins": Coins,
  "shopping-cart": ShoppingCart,
  "coffee": Coffee,
  "plug": Plug,
  "bank": Banknote,
  "car": Car,
  "shield": Shield,
  "heart": Heart,
  "book-open": BookOpen,
  "baby": Baby,
  "film": Film,
  "plane": Plane,
  "shirt": Shirt,
  "scissors": Scissors,
  "repeat": Repeat,
  "hand-heart": HandHeart,
  "tools": Wrench,
  "smartphone": Smartphone,
  "sofa": Sofa,
  "paw": PawPrint,
  "dumbbell": Dumbbell,
  "book": Book,
  "music": Music,
  "gamepad": Gamepad,
  "palette": Palette,
  "file-text": FileText,
  "wifi": Wifi,
  "tv": Tv,
  "play-circle": PlayCircle,
  "parking-circle": ParkingCircle,
  "road": Map,
  "bus": Bus,
  "alert-triangle": AlertTriangle,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  "life-buoy": LifeBuoy,
  "calendar": Calendar,
  "snowflake": Snowflake,
  "egg": Egg,
  "dice": Dice1,
  "wine": Wine,
  "smoking": Cigarette,
  "candy": Candy,
  "umbrella": Umbrella,
  "hotel": Hotel,

  // New icon mappings
  "fuel": Fuel,
  "shield-check": ShieldCheck,
  "settings-2": Settings2,
  "shield-plus": ShieldPlus,
  "landmark": Landmark,
  "graduation-cap": GraduationCap,
  "paint-roller": PaintRoller,
  "shopping-basket": ShoppingBasket,
  "arrow-right-left": ArrowRightLeft,
  "award": Award,
  "scale": Scale,
  "mail": Mail,
  "app-window": AppWindow,
  "wallet": Wallet,
  "utensils": Utensils,
  "more-horizontal": MoreHorizontal,
  "receipt": Receipt, 
  // Added mapping for Transaction Costs
};