import { 
  ShoppingBasket,
  Pizza,
  Home,
  Plug,
  Wifi,
  Bus,
  ShieldCheck,
  Stethoscope,
  Book,
  PiggyBank,
  Tv,
  Plane,
  Shirt,
  Scissors,
  Gift,
  Repeat,
  Wrench,
  PawPrint,
  Baby,
  TrendingUp,
  CreditCard,
  DollarSign,
  FileText,
  AlertTriangle,
  MoreHorizontal,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  "shopping-basket": ShoppingBasket,
  "pizza": Pizza,
  "home": Home,
  "plug": Plug,
  "wifi": Wifi,
  "bus": Bus,
  "shield-check": ShieldCheck,
  "stethoscope": Stethoscope,
  "book": Book,
  "piggy-bank": PiggyBank,
  "tv": Tv,
  "plane": Plane,
  "shirt": Shirt,
  "scissors": Scissors,
  "gift": Gift,
  "repeat": Repeat,
  "wrench": Wrench,
  "paw-print": PawPrint,
  "baby": Baby,
  "trending-up": TrendingUp,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  "file-text": FileText,
  "alert-triangle": AlertTriangle,
  "more-horizontal": MoreHorizontal,
}; 